const TRAINING_COPY = {
    'zh-CN': {
        home: {
            todayKicker: '今日训练',
            diagnosticTitle: '先做 3 分钟诊断',
            diagnosticBody: '完成三轮短测试后，系统会自动生成你的能力画像与 7 天起步计划。',
            todayFlowTitle: '今天从这三条路开始',
            todayFlowBody: '把最值得做的动作放到一屏，不用自己重新做决策。',
            diagnosticCta: '开始诊断',
            diagnosticResume: '继续诊断',
            dashboardTitle: '今天该练什么',
            dashboardBody: '系统会根据最近表现和当前计划，给你一个最值得继续的回合。',
            continuePlan: '继续今日任务',
            freePractice: '自由练习',
            freePracticeKicker: '快速热身',
            freePracticeBody: '不进入计划也能直接开一轮，用来热身、放松或验证手感。',
            levelLabel: '当前等级',
            streakLabel: '连续天数',
            weakLabel: '当前短板',
            planLabel: '计划进度',
            weekLabel: '近 7 天完成',
            weekGoalSuffix: '次',
            noWeakness: '继续扩大样本，系统会逐步收敛训练重点。'
        },
        diagnostic: {
            kicker: '能力画像',
            title: '用 3 分钟建立第一条训练主线',
            body: '这不是考试，而是一次定向采样。系统会根据准确率、节奏波动和数字符号表现，安排后续训练。',
            start: '开始诊断',
            resume: '继续诊断',
            stepTitle: '诊断步骤',
            activeTitle: '当前进度',
            done: '已完成',
            pending: '待完成'
        },
        practice: {
            taskKicker: '当前任务',
            diagnosticBadge: '诊断任务',
            planBadge: '计划任务',
            challengeBadge: '挑战任务',
            customSource: '自定义词库',
            customTitle: '把自己的词库塞进训练主线',
            customBody: '贴入单词、句子或段落后，这轮会直接用你的文本练习。',
            customPlaceholder: '在这里粘贴词库、术语表或你想重复练习的段落。',
            customApply: '使用这段文本',
            layoutLabel: '键盘布局'
        },
        result: {
            planTitle: '下一步动作',
            planBody: '这轮已经记入你的训练计划，直接继续下一步会比重新选模式更有效。',
            continuePlan: '继续计划',
            planComplete: '计划已完成',
            planCompleteBody: '这一轮已经把当前起步计划收尾，可以回首页查看新的成长建议。'
        },
        nav: {
            challenge: '挑战'
        },
        account: {
            title: '云端账户',
            body: '登录后可以同步训练历史、计划续接和挑战成绩。',
            idle: '尚未登录',
            connected: '已连接',
            loading: '连接中',
            error: '连接异常',
            nameLabel: '显示名称',
            namePlaceholder: '输入昵称',
            signIn: '登录并同步',
            signOut: '退出登录',
            export: '导出数据',
            import: '导入数据',
            importLabel: '导入 JSON',
            importPlaceholder: '粘贴导出的训练数据 JSON',
            importSuccess: '数据已导入本地工作区。'
        },
        challenge: {
            kicker: '今日挑战',
            title: '用同一轮文本比拼稳定输出',
            body: '挑战会固定文本和配置，方便比较速度与准确率。',
            cta: '开始挑战',
            retryCta: '再挑战一次',
            leaderboard: '今日榜单',
            viewBoard: '查看榜单',
            statusTitle: '你的今日战绩',
            statusEmpty: '还没参加今天的挑战，完成一轮后这里会显示你的名次和个人最佳。',
            statusReady: '今天已经上榜，继续冲一把更高的名次。',
            homeIdleNote: '完成一轮后，这里会直接显示你的今日名次。',
            homeReadyNote: '今天已经留下挑战成绩，可以继续刷新个人最佳。',
            historyTitle: '今日挑战回放',
            historyBody: '把今天的几次挑战摆在一起看，决定下一轮是继续提速还是稳准确率。',
            trendTitle: '今日挑战趋势',
            trendBody: '把今天几次挑战放进一条曲线里看，判断现在适合继续加压还是先稳住准确率。',
            trendEmpty: '至少完成两次挑战后，这里会更清楚地显示今天的变化趋势。',
            trendWarm: '再来一轮就能更清楚地看出今天的趋势。',
            trendFirstLabel: '第一次',
            trendLatestLabel: '最新一次',
            trendSpeedChangeLabel: '速度变化',
            trendAccuracyChangeLabel: '准确率变化',
            trendFocusTitle: '本次细看',
            trendPrevDeltaLabel: '较上次',
            trendRunLabel: '第 {value} 次',
            trendFocusBaseline: '这是今天的基线，用后续回合判断方向。',
            trendFocusBreakthrough: '这次提速没有明显牺牲准确率，可以继续保持挑战压力。',
            trendFocusAccuracyRisk: '速度可能来自准确率透支，下一轮先稍微放慢。',
            trendFocusSpeedDrop: '速度较上次回落，如果连续出现就先离开挑战模式。',
            trendFocusStable: '这次表现稳定，下一轮只适合小幅加压。',
            trendFocusMixed: '变化比较混合，先稳节奏再追更高名次。',
            trendImproving: '比今天第一次更快，适合继续冲击更高速度。',
            trendCooling: '今天后半段速度开始回落，建议先稳住节奏。',
            trendSteady: '今天整体比较稳定，可以继续小步加压。',
            strategyTitle: '下一步建议',
            strategyIdle: '先留下今天的第一条成绩，系统再判断是否值得继续冲榜。',
            strategyWarm: '再来一轮扩大样本，今天的真实状态会更清楚。',
            strategyImproving: '适合继续冲榜，今天的速度曲线还在向上。',
            strategyCooling: '先稳准确率，今天后半段已经开始回落。',
            strategyRecover: '今天这波冲榜已经开始透支，建议先切回计划训练或轻松练习。',
            strategySteady: '可以小步加压，今天整体比较平稳。',
            recoverPlanCta: '先回计划',
            recoverFreeCta: '先去热身',
            attemptsLabel: '今日尝试',
            bestRunLabel: '最佳速度',
            latestDeltaLabel: '距最佳',
            bestBadge: '最佳成绩',
            latestBadge: '最新成绩',
            peerTitle: '同级别对比',
            peerBody: '先和同等级选手比较，判断你在相近水平里的位置。',
            peerEmpty: '当前还没有同等级成绩，先留下你的第一条记录。',
            empty: '今天还没人交卷，你可以做第一名。'
        },
        insights: {
            radarTitle: '成长雷达',
            radarBody: '把等级、streak、周目标和计划进度放在同一屏里看。',
            weekGoal: '周目标',
            riskLow: '节奏稳定，可以继续加压。',
            riskHigh: '最近训练在变少，streak 有中断风险。',
            achievementsTitle: '成就墙',
            achievementsBody: '让训练关系被看见，不只是数字涨了。'
        }
    },
    'en-US': {
        home: {
            todayKicker: 'Today',
            diagnosticTitle: 'Start with a 3-minute assessment',
            diagnosticBody: 'Finish three short rounds and the system will build a skill profile plus a 7-day starter plan.',
            todayFlowTitle: 'Start from one of these lanes',
            todayFlowBody: 'Keep the best next actions in one screen so you do not have to rebuild the decision.',
            diagnosticCta: 'Start assessment',
            diagnosticResume: 'Resume assessment',
            dashboardTitle: 'What to train today',
            dashboardBody: 'The system picks the most useful next round from your recent performance and active plan.',
            continuePlan: 'Continue today\'s task',
            freePractice: 'Free practice',
            freePracticeKicker: 'Quick warm-up',
            freePracticeBody: 'Jump into a clean built-in round for warm-ups, cooldowns, or simple feel checks.',
            levelLabel: 'Current level',
            streakLabel: 'Streak',
            weakLabel: 'Current weakness',
            planLabel: 'Plan progress',
            weekLabel: 'Last 7 days',
            weekGoalSuffix: 'sessions',
            noWeakness: 'Keep expanding the sample and the plan will tighten around the real weak spots.'
        },
        diagnostic: {
            kicker: 'Skill profile',
            title: 'Use 3 minutes to define the first training path',
            body: 'This is not a test score. It is a short sample used to map accuracy, rhythm, and symbol readiness into a plan.',
            start: 'Start assessment',
            resume: 'Resume assessment',
            stepTitle: 'Assessment steps',
            activeTitle: 'Current progress',
            done: 'Done',
            pending: 'Pending'
        },
        practice: {
            taskKicker: 'Current task',
            diagnosticBadge: 'Assessment',
            planBadge: 'Planned drill',
            challengeBadge: 'Challenge round',
            customSource: 'Custom bank',
            customTitle: 'Bring your own word bank into the plan',
            customBody: 'Paste words, sentences, or a paragraph and this round will train directly on that text.',
            customPlaceholder: 'Paste your glossary, phrases, or repeatable text here.',
            customApply: 'Use this text',
            layoutLabel: 'Keyboard layout'
        },
        result: {
            planTitle: 'Next action',
            planBody: 'This round already updated your plan. Continuing directly is usually better than choosing a fresh mode manually.',
            continuePlan: 'Continue plan',
            planComplete: 'Plan complete',
            planCompleteBody: 'This starter plan is finished. Head back home to review the next growth recommendation.'
        },
        nav: {
            challenge: 'Challenge'
        },
        account: {
            title: 'Cloud account',
            body: 'Sign in to sync history, resume plans across devices, and submit challenge results.',
            idle: 'Not signed in',
            connected: 'Connected',
            loading: 'Connecting',
            error: 'Connection issue',
            nameLabel: 'Display name',
            namePlaceholder: 'Enter a display name',
            signIn: 'Sign in and sync',
            signOut: 'Sign out',
            export: 'Export data',
            import: 'Import data',
            importLabel: 'Import JSON',
            importPlaceholder: 'Paste exported training JSON here',
            importSuccess: 'Training data was imported into the local workspace.'
        },
        challenge: {
            kicker: 'Daily challenge',
            title: 'Compare one shared round with steady output',
            body: 'The challenge locks the text and setup so speed and accuracy stay comparable.',
            cta: 'Start challenge',
            retryCta: 'Retry challenge',
            leaderboard: 'Leaderboard',
            viewBoard: 'View leaderboard',
            statusTitle: 'Your challenge status',
            statusEmpty: 'No result posted yet. Finish one round and your rank plus best status will appear here.',
            statusReady: 'You are already on today\'s board. Push again to chase a better rank.',
            homeIdleNote: 'Finish one round and this card will start showing today\'s rank.',
            homeReadyNote: 'Your result is already on the board. Push again to set a better mark.',
            historyTitle: 'Today\'s replay',
            historyBody: 'Review the challenge attempts from today and decide whether the next round should push speed or protect accuracy.',
            trendTitle: 'Today\'s trend',
            trendBody: 'Put today\'s challenge runs on one curve so it is obvious whether you should push harder or stabilize accuracy first.',
            trendEmpty: 'After at least two challenge runs, today\'s trend will become much clearer here.',
            trendWarm: 'One more run will make today\'s pattern much clearer.',
            trendFirstLabel: 'First run',
            trendLatestLabel: 'Latest run',
            trendSpeedChangeLabel: 'Speed change',
            trendAccuracyChangeLabel: 'Accuracy change',
            trendFocusTitle: 'Run focus',
            trendPrevDeltaLabel: 'Vs previous',
            trendRunLabel: 'Run {value}',
            trendFocusBaseline: 'This is today\'s baseline. Use later runs to judge the direction.',
            trendFocusBreakthrough: 'This run gained speed without giving up accuracy. Keep the challenge pressure on.',
            trendFocusAccuracyRisk: 'Speed may be coming from accuracy leakage. Slow the next run down slightly.',
            trendFocusSpeedDrop: 'Speed dropped against the previous run. Step out of challenge mode if this repeats.',
            trendFocusStable: 'This run held steady. Add only a small amount of pressure next.',
            trendFocusMixed: 'The change is mixed. Protect rhythm before chasing a higher rank.',
            trendImproving: 'You are faster than the first run today. This is a good moment to keep pushing.',
            trendCooling: 'Speed is fading later in the day. It may be better to stabilize rhythm first.',
            trendSteady: 'Today is holding fairly steady. You can keep increasing pressure in small steps.',
            strategyTitle: 'Next move',
            strategyIdle: 'Post the first result today and the app can start judging whether it is worth pushing harder.',
            strategyWarm: 'Take one more run to expand the sample and reveal today\'s real shape.',
            strategyImproving: 'Keep pushing the board. Today\'s speed curve is still moving upward.',
            strategyCooling: 'Protect accuracy first. The later runs are already starting to cool down.',
            strategyRecover: 'The leaderboard push is flattening out. Step away from challenge mode and return to plan work.',
            strategySteady: 'Apply a small increase in pressure. Today looks stable enough to try again.',
            recoverPlanCta: 'Back to plan',
            recoverFreeCta: 'Free practice',
            attemptsLabel: 'Attempts today',
            bestRunLabel: 'Best speed',
            latestDeltaLabel: 'Gap to best',
            bestBadge: 'Best run',
            latestBadge: 'Latest run',
            peerTitle: 'Peer group',
            peerBody: 'Compare with players at the same level first to understand your relative position.',
            peerEmpty: 'No same-level results yet. You can leave the first one.',
            empty: 'No one has posted a result yet. You can take the first spot.'
        },
        insights: {
            radarTitle: 'Growth radar',
            radarBody: 'Review level, streak, weekly goal, and plan progress in one place.',
            weekGoal: 'Weekly goal',
            riskLow: 'Your training rhythm is healthy enough to keep pushing.',
            riskHigh: 'Recent activity is dropping. Your streak is starting to wobble.',
            achievementsTitle: 'Achievement wall',
            achievementsBody: 'Make the training relationship visible, not just the raw numbers.'
        }
    }
};

export function getTrainingCopy(language = 'zh-CN') {
    return TRAINING_COPY[language] || TRAINING_COPY['zh-CN'];
}
